### ISSUE TITLE
Whether to support dxf file parsing?

### ISSUE THREAD

**Issue by hanxuanliang** [deadsy/sdfx#78]
I am a newcomer and was searching for dxf topic on github and found this library. Not sure if dxf files are supported?

**Comment by deadsy** [comment]
You can take a 2d SDF and output it as a dxf file.

Example: https://github.com/deadsy/sdfx/blob/master/examples/text/main.go

The render.ToDXF() will run marching squares on the SDF and then write the resulting line segments out to the DXF file.

Reading a DXF file is a different proposition because in general a DXF file will not cleanly represent the boundary of a SDF.

**Comment by hanxuanliang** [comment]
Is there an API that can read and write dxf files directly?

**Comment by deadsy** [comment]
https://github.com/yofu/dxf
